app:
  stylesheets: ['https://codepen.io/chriddyp/pen/bWLwgP.css']
data:
  cdr:
    path: data/all_cdrs.bed.gz
    position: relative
    type: bed
    prop: 0.1
  methyl:
    path: data/all_CpG_methyl.bedgraph.gz
    position: relative
    type: bedgraph
    prop: 0.5
  as_hor_stv:
    path: data/all_AS-HOR_stv_row.bed.gz
    position: relative
    type: bed
    prop: 0.34
  sat_annot:
    path: data/all_RM_satellite_annotation.bed.gz
    position: overlap
    type: bed
  as_hor_strand:
    path: data/all_AS-HOR_stv_row_strand.bed.gz
    position: relative
    type: bedstrand
    prop: 0.1
  # moddotplot:
  #   path: data/all_ModDotPlot.bed.gz
  #   position: relative
  #   type: bedpe_selfident
  #   prop: 2.0
regions: data/all_array.bed.gz
clades: data/clades.tsv.gz
sample_metadata: data/sample_metadata.tsv.gz
