general:
  fig_1:
    bboxes: assets/Figure1_chrom_bboxes.csv
    order: assets/Figure1_order.csv
    use_data:
    - "CDR"
    - "CpG Methylation"
    - "Satellite Structure"
    - "Alpha-satellite HORs"
  tree:
    # Tree height
    height: 100vh
    # Tree width (x / 12)
    width: 6
    # Midpoint of tree. Defaults to half of the image.
    xmidpt:
      chr13: 4000
      chr14: 4000
      chr15: 4030
      chr21: 4160
      chr22: 4160
      default: null
    # Starting y-position of first centromere in tree
    ystart:
      chr13: 601
      chr14: 601
      chr15: 601
      chr21: 601
      chr22: 601
      default: 608
    # Offset in y-position to reach next centromere
    # Applied to both acro and other chromosomes
    yoffset:
      default: 77
  selected_cen:
    # Selected centromere height
    height: 45vh
    # Centromere plot width (x / 12)
    width: 6
    # Vertical space between tracks
    vspace: 0.05
    # Left, right, bottom, and top margin of selected cen plot
    lmargin: 100
    rmargin: 0
    bmargin: 0
    tmargin: 0
# Tracks
data:
  # Unique label
  "MEI":
    # Path to bgzipped bed file
    path: data/all_MEI.bed.gz
    # Relative or overlap
    position: relative
    # bed, bedgraph, bedstrand, bed_localselfident
    type: bed
    # Proportion
    prop: 0.01
    options:
      # Run-length encode same names
      rle: false
      # Shape of marker (tri or rect)
      shape: tri
      # Slop record for marker. Data remains same.
      bp_slop: 10000
      # Plotly axes keyword arguments
      # https://plotly.com/python/reference/layout/xaxis/
      # https://plotly.com/python/reference/layout/yaxis/
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        # Title text converted to annotation since plotly does not support rotated titles
        title_text: MEIs
        showticklabels: false
        ticks: ""
        showline: false
  "CDR":
    path: data/all_cdrs.bed.gz
    position: relative
    type: bed
    prop: 0.01
    options:
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: CDRs
        showticklabels: false
        ticks: ""
        showline: false
  "CpG Methylation":
    path: data/all_CpG_methyl.bedgraph.gz
    position: relative
    type: bedgraph
    prop: 0.25
    options:
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "CpG<br>Methylation"
        showline: false
  "Satellite Structure":
    path: data/all_RM_satellite_annotation.bed.gz
    position: relative
    type: bed
    prop: 0.1
    options:
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Satellite<br>Structure"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HORs":
    path: data/all_AS-HOR_stv_row.bed.gz
    position: overlap
    type: bed
    options:
      rle: true
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        showticklabels: false
        ticks: ""
        showline: false
  "Local Self-Identity":
    path: data/all_local_self_identity.bed.gz
    position: relative
    type: bed_localselfident
    prop: 0.01
    options:
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Local<br>Self-Identity"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HOR array orientation":
    path: data/all_AS-HOR_stv_row_strand.bed.gz
    position: relative
    type: bedstrand
    prop: 0.05
    options:
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "α-satellite<br>HOR strand"
        showticklabels: false
        ticks: ""
        showline: false
  # "Self-Identity":
  #   path: data/all_ModDotPlot.bed.gz
  #   position: relative
  #   type: bedpe_selfident
  #   prop: 4.0
regions: data/all_array.bed.gz
clades: data/clades.tsv.gz
sample_metadata: data/sample_metadata.tsv.gz
population_colors: data/all_population_colors.tsv
