general:
  # Title of app
  title: Cencyclopedia
  # Mode to run {all, single}
  mode: single
  # Output regions
  output_regions: data/bed_single.csv.gz
  # Regions bedfile
  regions: data/all_array.bed.gz
  selected_cen:
    # Selected centromere height
    height: 800
    # Centromere plot width (x / 12)
    width: 5
    # y-axis title position. left or right. Should also adjust margins below to accomodate.
    ytitle_pos: left
    # y-axis title borderpad pad
    ytitle_borderpad: 20
    # Left, right, bottom, and top margin of selected cen plot
    lmargin: 140
    rmargin: 0
    bmargin: 0
    tmargin: 0
    # 0.0 for autosize
    vertical_spacing: 0.0
    # Selected tab for data view.
    default_data_tab: "Alpha-satellite HORs"
# Tracks
data:
  # Unique label
  "MEI":
    # Path to bgzipped bed file
    path: data/all_MEI.bed.gz
    # Relative or overlap
    position: relative
    # bed, bedgraph, bedstrand, bed_localselfident
    type: bed
    # Proportion
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "MEI"
        color: "Color"
        score: "Score"
      # Run-length encode same names
      rle: false
      # Shape of marker (tri or rect)
      shape: tri
      # Slop record for marker. Data remains same.
      bp_slop: 50000
      # Plotly axes keyword arguments
      # https://plotly.com/python/reference/layout/xaxis/
      # https://plotly.com/python/reference/layout/yaxis/
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        # Title text converted to annotation since plotly does not support rotated titles
        title_text: MEI(s)
        showticklabels: false
        ticks: ""
        showline: false
  "Spacer":
    position: relative
    type: spacer
    prop: 0.02
    options:
      xaxis_kwargs:
        showticklabels: false
        ticks: ""
        showline: false
      yaxis_kwargs:
        showticklabels: false
        ticks: ""
        showline: false
  "CDR":
    path: data/all_cdrs.bed.gz
    position: relative
    type: bed
    prop: 0.01
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "CDR"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: CDR(s)
        showticklabels: false
        ticks: ""
        showline: false
  "CpG Methylation":
    path: data/all_CpG_methyl.bedgraph.gz
    position: relative
    type: bedgraph
    prop: 0.1
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Average CpG Methylation"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        range: [0.0, 1.0]
        title_text: "CpG<br>Methylation"
  "Structure":
    path: data/all_RM_satellite_annotation.bed.gz
    position: relative
    type: bed
    prop: 0.05
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Structure"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Structure"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HORs":
    path: data/all_AS-HOR_stv_row.bed.gz
    # position: relative
    position: overlap
    type: bed
    # prop: 0.05
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "α-satellite HOR"
        color: "Color"
        score: "Monomers"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "α-satellite HORs"
        showticklabels: false
        ticks: ""
        showline: false
  "Local Self-Identity":
    path: data/all_local_self_identity.bed.gz
    position: relative
    type: bed_localselfident
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Identity Range"
        color: "Color"
        score: "Percent Identity"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Local Self-Identity"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HOR array orientation":
    path: data/all_AS-HOR_stv_row_strand.bed.gz
    position: relative
    type: bedstrand
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Strand"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Orientation"
        showticklabels: false
        ticks: ""
        showline: false
  "Self-Identity":
    # If dir, will expect ${dir}/${contig}.bed.gz
    path: data/ModDotPlot/
    position: relative
    type: bedpe_selfident
    prop: 0.5
    options:
      replace_colnames:
        qry: "Query Contig"
        qry_st: "Query Start"
        qry_end: "Query End"
        ref: "Reference Contig"
        ref_st: "Reference Start"
        ref_end: "Reference End"
        percent_identity_by_events: "Percent Identity"
      rle: false
      xaxis_kwargs:
        title_text: "Genomic Position"
        showline: true
      yaxis_kwargs:
        showline: false
        showticklabels: false
        ticks: ""
        title_text: Self-Identity
