general:
  # Title of app
  title: Cencyclopedia
  # Mode to run {all, single}
  mode: all
  # Output regions
  output_regions: data/hgsvc/bed.csv.gz
  # Regions bedfile
  regions: data/hgsvc/all_array.bed.gz
  # Clades (all)
  clades: data/hgsvc/clades.tsv.gz
  # Sample metadata (all)
  sample_metadata: data/hgsvc/sample_metadata.tsv.gz
  # Continental_group colors (all)
  continental_group_colors: data/hgsvc/all_continental_group_colors.tsv
  # Other settings
  chrom_navlink:
    bboxes: assets/hgsvc/Chromosomes.bboxes.csv
  fig_1:
    bboxes: assets/hgsvc/Figure1_chrom_bboxes.csv
    order: assets/hgsvc/Figure1_order.csv
    height_figure: 100vh
    height_cens: 34vh
    use_data:
    - "MEI"
    - "Spacer"
    - "CDR"
    - "CpG methylation"
    - "Structure"
    - "Alpha-satellite HORs"
    - "Local self-identity"
    - "Alpha-satellite HOR array orientation"
    - "Self-identity"
  tree:
    # Tree height
    height: 200vh
    # Tree width (x / 12)
    width: 7
    # Midpoint of tree. Defaults to half of the image.
    xmidpt:
      chr13: 2000
      chr14: 2000
      chr15: 2015
      chr21: 2080
      chr22: 2080
      default: null
    # Starting y-position of first centromere in tree
    ystart:
      chr13: 301
      chr14: 301
      chr15: 301
      chr21: 301
      chr22: 301
      default: 304
    # Offset in y-position to reach next centromere
    # Applied to both acro and other chromosomes
    yoffset:
      default: 38.5
  selected_cen:
    # Selected centromere height
    height: 400
    # Centromere plot width (x / 12)
    width: 5
    # y-axis title position. left or right. Should also adjust margins below to accomodate.
    ytitle_pos: left
    # y-axis title borderpad pad
    ytitle_borderpad: 20
    # Left, right, bottom, and top margin of selected cen plot
    lmargin: 140
    rmargin: 0
    bmargin: 0
    tmargin: 0
    # 0.0 for autosize
    vertical_spacing: 0.005
    # Selected tab for data view.
    default_data_tab: "Alpha-satellite HORs"
# Tracks
data:
  # Unique label
  "MEI":
    # Path to bgzipped bed file
    path: data/hgsvc/all_MEI.bed.gz
    # Relative or overlap
    position: relative
    # bed, bedgraph, bedstrand, bed_localselfident
    type: bed
    # Proportion
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "MEI"
        color: "Color"
        score: "Score"
      # Run-length encode same names
      rle: false
      # Shape of marker (tri or rect)
      shape: tri
      # Slop record for marker. Data remains same.
      bp_slop: 50000
      # Plotly axes keyword arguments
      # https://plotly.com/python/reference/layout/xaxis/
      # https://plotly.com/python/reference/layout/yaxis/
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        # Title text converted to annotation since plotly does not support rotated titles
        title_text: MEI(s)
        showticklabels: false
        ticks: ""
        showline: false
  "Spacer":
    position: relative
    type: spacer
    prop: 0.02
    options:
      xaxis_kwargs:
        showticklabels: false
        ticks: ""
        showline: false
      yaxis_kwargs:
        showticklabels: false
        ticks: ""
        showline: false
  "CDR":
    path: data/hgsvc/all_cdrs.bed.gz
    position: relative
    type: bed
    prop: 0.01
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "CDR"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: CDR(s)
        showticklabels: false
        ticks: ""
        showline: false
  "CpG methylation":
    path: data/hgsvc/all_CpG_methyl.bedgraph.gz
    position: relative
    type: bedgraph
    prop: 0.1
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Average CpG methylation"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        range: [0.0, 1.0]
        title_text: "CpG<br>methylation"
  "Structure":
    path: data/hgsvc/all_RM_satellite_annotation.bed.gz
    position: relative
    type: bed
    prop: 0.05
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Structure"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Structure"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HORs":
    path: data/hgsvc/all_AS-HOR_stv_row.bed.gz
    # position: relative
    position: overlap
    type: bed
    # prop: 0.05
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "α-satellite HOR"
        color: "Color"
        score: "Monomers"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "α-satellite HORs"
        showticklabels: false
        ticks: ""
        showline: false
  "Local self-identity":
    path: data/hgsvc/all_local_self_identity.bed.gz
    position: relative
    type: bed_localselfident
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Identity range"
        color: "Color"
        score: "Percent identity"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Local self-identity"
        showticklabels: false
        ticks: ""
        showline: false
  "Alpha-satellite HOR array orientation":
    path: data/hgsvc/all_AS-HOR_stv_row_strand.bed.gz
    position: relative
    type: bedstrand
    prop: 0.02
    options:
      replace_colnames:
        chrom: "Contig"
        chrom_st: "Start"
        chrom_end: "End"
        name: "Strand"
        color: "Color"
        score: "Score"
      rle: false
      xaxis_kwargs:
        ticks: ""
        showline: false
      yaxis_kwargs:
        title_text: "Orientation"
        showticklabels: false
        ticks: ""
        showline: false
  "Self-identity":
    # If dir, will expect ${dir}/${contig}.bed.gz
    path: data/hgsvc/ModDotPlot/
    position: relative
    type: bedpe_selfident
    prop: 0.5
    options:
      replace_colnames:
        qry: "Query contig"
        qry_st: "Query start"
        qry_end: "Query end"
        ref: "Reference contig"
        ref_st: "Reference start"
        ref_end: "Reference end"
        percent_identity_by_events: "Percent identity"
      rle: false
      xaxis_kwargs:
        title_text: "Genomic position"
        showline: true
      yaxis_kwargs:
        showline: false
        showticklabels: false
        ticks: ""
        title_text: Self-identity
